FROM node:6-alpine

RUN mkdir -p /var/www /var/www/node_modules
WORKDIR /var/www

RUN npm install -g babel-cli@6

ADD ./widget/package.json /var/www/package.json
RUN npm install

RUN npm install rollup --global

CMD rollup -w -c
