version: "2"
services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile-react
    user: node
    container_name: react
    hostname: react
    volumes:
      - ./widget:/var/www
      - /var/www/node_modules

  website:
    image: nginx:alpine
    container_name: website
    hostname: website
    volumes:
      - ./nginx/website.conf:/etc/nginx/conf.d/website.conf
      - ./nginx/public:/var/www/public
      - ./widget/build:/var/www/public/widget
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
