version: "2"
services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile-react
    user: root
    container_name: react
    hostname: react
    tty: true
    volumes:
      - ./widget:/var/www
      - /var/www/node_modules
    ports:
      - 3000:3000

  website:
    image: nginx:alpine
    container_name: website
    hostname: website
    volumes:
      - ./nginx/website.conf:/etc/nginx/conf.d/website.conf
      - ./widget/build:/var/www/public
    ports:
      - 8080:8080
