version: "2"
services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile-react
    user: root
    container_name: react
    hostname: react
    tty: true
    volumes:
      - ./widget:/var/www
      - /var/www/node_modules
    ports:
      - 3000:3000
