FROM node:6-alpine

RUN mkdir -p /var/www /var/www/node_modules
WORKDIR /var/www

RUN npm install -g babel-cli@6

ADD ./widget/package.json /var/www/package.json
RUN npm install

CMD babel --watch src --out-dir build --presets react-app/prod
